name: build push image for deployment
on:
  push:
    branches:
      - main
jobs:
  build-section:
    environment: action
    runs-on: ubuntu-latest

    steps:
      - name: print something
        run: echo "Spring-Modulith"
      - name: show host environment variables
        run: echo "Actuator endpoints $ACTUATOR_EXPOSED_ENDPOINTS"



#  push-image-section