name: build push image for deployment
on:
  push:
    branches:
      - main
jobs:
  sample-job-section:
    environment: action
    runs-on: ubuntu-latest

    steps:
      - name: print something
        run: echo "Spring-Modulith"
      - name: show host environment variables
        run: echo "Actuator endpoints ${{vars.ACTUATOR_EXPOSED_ENDPOINTS}}"

  build-job-section:
    environment: action
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: action/checkout@v4
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'maven'
#          cache-dependency-path: 'sub-project/pom.xml' # optional
#      - name: Build with Maven
#        run: mvn -B package --file pom.xml

#  push-image-section