name: build push image for deployment
on:
  push:
    branches:
      - main
jobs:
  build-section:
    environment: action
    runs-on: ubuntu-latest

    steps:
      - name: print something
        run: echo "Spring-Modulith"


#  push-image-section